image: registry.git.rwth-aachen.de/acplt/build-docker-image/rte-crossbuild


build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=export ..
    - make -j$(nproc)
    - make install
  artifacts:
    paths:
      - build/export
      - build/core/acplt_builder/acplt_builder

build-win32-x64:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc) ov_codegen
    - cd ..
    - mkdir build-win32
    - cd build-win32
    - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/mingw-w64-x86_64.cmake -DOV_CODEGEN_PATH="../build/core/codegen/ov_codegen" -DCMAKE_INSTALL_PREFIX=export ..
    - make -j$(nproc)
    - make install
  artifacts:
    paths:
      - build-win32/export

build-linux-armhf:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc) ov_codegen
    - cd ..
    - mkdir build-linux-armhf
    - cd build-linux-armhf
    - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/gcc-linux-armhf.cmake -DOV_CODEGEN_PATH="../build/core/codegen/ov_codegen" -DCMAKE_INSTALL_PREFIX=export ..
    - make -j$(nproc)
    - make install
  artifacts:
    paths:
      - build-linux-armhf/export

test_acplt_builder:
  stage: test
  dependencies:
    - build
  script:
    - cd syslibs/ssc
    - export OV_LIBRARY_PATH=":../../core"
    - ../../build/core/acplt_builder/acplt_builder -l model/ssc.ovm
    - "[ -f \"source/sourcetemplates/actionBlock.c\" ]"
